import type {
  course,
  courseTag,
  lesson,
  opportunity,
  opportunityTag,
  quizOption,
  quizQuestion,
  tag,
} from "@/db/schema"

const date = (value: string) => new Date(`${value}T00:00:00.000Z`)

export const seedTags = [
  { id: "tag:stem", slug: "stem", name: "STEM", kind: "field", color: "teal" },
  {
    id: "tag:business",
    slug: "business",
    name: "Business",
    kind: "field",
    color: "amber",
  },
  {
    id: "tag:social-impact",
    slug: "social-impact",
    name: "Social Impact",
    kind: "field",
    color: "green",
  },
  {
    id: "tag:finance",
    slug: "finance",
    name: "Finance",
    kind: "field",
    color: "blue",
  },
  {
    id: "tag:programming",
    slug: "programming",
    name: "Programming",
    kind: "field",
    color: "violet",
  },
  {
    id: "tag:science",
    slug: "science",
    name: "Science",
    kind: "field",
    color: "cyan",
  },
  {
    id: "tag:mathematics",
    slug: "mathematics",
    name: "Mathematics",
    kind: "subject",
    color: "teal",
  },
  {
    id: "tag:english",
    slug: "english",
    name: "English",
    kind: "subject",
    color: "blue",
  },
  {
    id: "tag:physics",
    slug: "physics",
    name: "Physics",
    kind: "subject",
    color: "cyan",
  },
  {
    id: "tag:economics",
    slug: "economics",
    name: "Economics",
    kind: "subject",
    color: "amber",
  },
  {
    id: "tag:computer-science",
    slug: "computer-science",
    name: "Computer Science",
    kind: "subject",
    color: "violet",
  },
  {
    id: "tag:sat-ielts",
    slug: "sat-ielts",
    name: "SAT / IELTS",
    kind: "subject",
    color: "rose",
  },
  {
    id: "tag:university-admission",
    slug: "university-admission",
    name: "University Admission",
    kind: "goal",
    color: "blue",
  },
  {
    id: "tag:portfolio",
    slug: "portfolio",
    name: "Portfolio Building",
    kind: "goal",
    color: "violet",
  },
  {
    id: "tag:research",
    slug: "research",
    name: "Research",
    kind: "goal",
    color: "cyan",
  },
  {
    id: "tag:scholarships",
    slug: "scholarships",
    name: "Scholarships",
    kind: "goal",
    color: "green",
  },
  {
    id: "tag:career-exploration",
    slug: "career-exploration",
    name: "Career Exploration",
    kind: "goal",
    color: "amber",
  },
  {
    id: "tag:hackathons",
    slug: "hackathons",
    name: "Hackathons",
    kind: "category",
    color: "violet",
  },
  {
    id: "tag:olympiads",
    slug: "olympiads",
    name: "Olympiads",
    kind: "category",
    color: "teal",
  },
  {
    id: "tag:summer-programs",
    slug: "summer-programs",
    name: "Summer Programs",
    kind: "category",
    color: "orange",
  },
] satisfies Array<typeof tag.$inferInsert>

export const seedOpportunities = [
  {
    id: "opportunity:central-asia-youth-hackathon",
    slug: "central-asia-youth-hackathon",
    title: "Central Asia Youth Hackathon",
    summary:
      "A weekend product-building challenge for students solving education and sustainability problems.",
    description:
      "Students form teams, prototype a digital solution, and pitch to mentors from regional startups. Beginners can join workshops before the final build sprint.",
    category: "hackathon",
    format: "hybrid",
    providerName: "Mentoria Labs",
    location: "Astana and online",
    country: "Kazakhstan",
    city: "Astana",
    minGrade: 9,
    maxGrade: 11,
    deadlineAt: date("2026-08-10"),
    startsAt: date("2026-08-21"),
    endsAt: date("2026-08-23"),
    applyUrl: "https://example.com/central-asia-youth-hackathon",
    requirements: [
      "Team of 2-4 students",
      "Basic presentation deck",
      "Prototype or demo by final pitch",
    ],
    isFeatured: true,
    isPublished: true,
  },
  {
    id: "opportunity:kazakhstan-junior-stem-olympiad",
    slug: "kazakhstan-junior-stem-olympiad",
    title: "Kazakhstan Junior STEM Olympiad",
    summary:
      "A national olympiad-style contest across math, physics, and computational thinking.",
    description:
      "Participants complete an online qualifying round followed by an in-person regional final. Strong performers receive mentorship for international competitions.",
    category: "olympiad",
    format: "offline",
    providerName: "KazSTEM Association",
    location: "Regional testing centers",
    country: "Kazakhstan",
    minGrade: 8,
    maxGrade: 11,
    deadlineAt: date("2026-09-20"),
    startsAt: date("2026-10-05"),
    endsAt: date("2026-10-06"),
    applyUrl: "https://example.com/kazakhstan-junior-stem-olympiad",
    requirements: ["School transcript", "Teacher contact", "Online qualifier"],
    isFeatured: true,
    isPublished: true,
  },
  {
    id: "opportunity:national-business-case-challenge",
    slug: "national-business-case-challenge",
    title: "National Business Case Challenge",
    summary:
      "A business strategy competition where students analyze a real market-entry case.",
    description:
      "Teams receive a case packet, build a recommendation, and defend it in front of entrepreneurs and finance professionals.",
    category: "competition",
    format: "online",
    providerName: "Future Founders KZ",
    country: "Kazakhstan",
    minGrade: 9,
    maxGrade: 11,
    deadlineAt: date("2026-09-01"),
    startsAt: date("2026-09-12"),
    endsAt: date("2026-09-19"),
    applyUrl: "https://example.com/national-business-case-challenge",
    requirements: ["Team of 3-5 students", "One-page motivation statement"],
    isFeatured: false,
    isPublished: true,
  },
  {
    id: "opportunity:global-youth-research-program",
    slug: "global-youth-research-program",
    title: "Global Youth Research Program",
    summary:
      "An online research mentorship program for students preparing science fair or university portfolios.",
    description:
      "Students work with a mentor to define a research question, read papers, collect data, and prepare a final poster.",
    category: "research",
    format: "online",
    providerName: "Open Science Academy",
    minGrade: 10,
    maxGrade: 11,
    deadlineAt: date("2026-10-01"),
    startsAt: date("2026-10-14"),
    endsAt: date("2026-12-18"),
    applyUrl: "https://example.com/global-youth-research-program",
    requirements: [
      "Research interest statement",
      "English reading ability",
      "Weekly availability",
    ],
    isFeatured: true,
    isPublished: true,
  },
  {
    id: "opportunity:future-leaders-summer-school",
    slug: "future-leaders-summer-school",
    title: "Future Leaders Summer School",
    summary:
      "A selective summer school on leadership, economics, and university preparation.",
    description:
      "The program combines seminars, admissions workshops, community projects, and mentor-led reflection sessions.",
    category: "summer_school",
    format: "offline",
    providerName: "Almaty Education Foundation",
    location: "Almaty",
    country: "Kazakhstan",
    city: "Almaty",
    minGrade: 9,
    maxGrade: 11,
    deadlineAt: date("2027-03-15"),
    startsAt: date("2027-06-15"),
    endsAt: date("2027-06-28"),
    applyUrl: "https://example.com/future-leaders-summer-school",
    requirements: [
      "Academic record",
      "Essay",
      "Recommendation from teacher or mentor",
    ],
    isFeatured: false,
    isPublished: true,
  },
  {
    id: "opportunity:green-impact-volunteering-sprint",
    slug: "green-impact-volunteering-sprint",
    title: "Green Impact Volunteering Sprint",
    summary:
      "A four-week volunteering project focused on environmental awareness campaigns.",
    description:
      "Students design a local action plan, run a small campaign, and document measurable community impact.",
    category: "volunteering",
    format: "hybrid",
    providerName: "EcoStep Central Asia",
    country: "Kazakhstan",
    minGrade: 8,
    maxGrade: 11,
    deadlineAt: date("2026-07-30"),
    startsAt: date("2026-08-05"),
    endsAt: date("2026-09-02"),
    applyUrl: "https://example.com/green-impact-volunteering-sprint",
    requirements: ["Local project idea", "Parent consent for offline events"],
    isFeatured: false,
    isPublished: true,
  },
  {
    id: "opportunity:high-school-data-science-internship",
    slug: "high-school-data-science-internship",
    title: "High School Data Science Internship",
    summary:
      "A remote internship introducing students to spreadsheets, Python notebooks, and data storytelling.",
    description:
      "Interns clean public datasets, build charts, and present a short analysis portfolio reviewed by mentors.",
    category: "internship",
    format: "online",
    providerName: "DataBridge Mentors",
    minGrade: 10,
    maxGrade: 11,
    deadlineAt: date("2026-11-05"),
    startsAt: date("2026-11-16"),
    endsAt: date("2027-01-15"),
    applyUrl: "https://example.com/high-school-data-science-internship",
    requirements: ["Basic algebra", "Laptop access", "Short diagnostic task"],
    isFeatured: false,
    isPublished: true,
  },
  {
    id: "opportunity:undergraduate-prep-scholarship",
    slug: "undergraduate-prep-scholarship",
    title: "Undergraduate Prep Scholarship",
    summary:
      "A scholarship covering SAT or IELTS preparation and admissions mentorship for motivated students.",
    description:
      "Recipients receive test-prep access, essay coaching, and deadline planning support for international university applications.",
    category: "scholarship",
    format: "online",
    providerName: "Mentoria Access Fund",
    minGrade: 10,
    maxGrade: 11,
    deadlineAt: date("2026-12-01"),
    startsAt: date("2027-01-10"),
    endsAt: date("2027-05-15"),
    applyUrl: "https://example.com/undergraduate-prep-scholarship",
    requirements: [
      "Financial need statement",
      "Academic record",
      "Admissions goals",
    ],
    isFeatured: true,
    isPublished: true,
  },
] satisfies Array<typeof opportunity.$inferInsert>

export const seedOpportunityTags = [
  ["opportunity:central-asia-youth-hackathon", "tag:hackathons"],
  ["opportunity:central-asia-youth-hackathon", "tag:programming"],
  ["opportunity:central-asia-youth-hackathon", "tag:stem"],
  ["opportunity:central-asia-youth-hackathon", "tag:portfolio"],
  ["opportunity:kazakhstan-junior-stem-olympiad", "tag:olympiads"],
  ["opportunity:kazakhstan-junior-stem-olympiad", "tag:stem"],
  ["opportunity:kazakhstan-junior-stem-olympiad", "tag:mathematics"],
  ["opportunity:kazakhstan-junior-stem-olympiad", "tag:physics"],
  ["opportunity:national-business-case-challenge", "tag:business"],
  ["opportunity:national-business-case-challenge", "tag:finance"],
  ["opportunity:national-business-case-challenge", "tag:economics"],
  ["opportunity:national-business-case-challenge", "tag:portfolio"],
  ["opportunity:global-youth-research-program", "tag:research"],
  ["opportunity:global-youth-research-program", "tag:science"],
  ["opportunity:global-youth-research-program", "tag:portfolio"],
  ["opportunity:future-leaders-summer-school", "tag:summer-programs"],
  ["opportunity:future-leaders-summer-school", "tag:business"],
  ["opportunity:future-leaders-summer-school", "tag:university-admission"],
  ["opportunity:green-impact-volunteering-sprint", "tag:social-impact"],
  ["opportunity:green-impact-volunteering-sprint", "tag:portfolio"],
  ["opportunity:high-school-data-science-internship", "tag:programming"],
  ["opportunity:high-school-data-science-internship", "tag:computer-science"],
  ["opportunity:high-school-data-science-internship", "tag:career-exploration"],
  ["opportunity:undergraduate-prep-scholarship", "tag:scholarships"],
  ["opportunity:undergraduate-prep-scholarship", "tag:sat-ielts"],
  ["opportunity:undergraduate-prep-scholarship", "tag:university-admission"],
] satisfies Array<
  [
    typeof opportunityTag.$inferInsert.opportunityId,
    typeof opportunityTag.$inferInsert.tagId,
  ]
>

export const seedCourses = [
  {
    id: "course:fundamentals-of-mathematics",
    slug: "fundamentals-of-mathematics",
    title: "Fundamentals of Mathematics",
    summary:
      "Strengthen algebra, functions, and problem-solving habits for olympiads and admissions tests.",
    description:
      "A practical math course for grades 8-11 covering core algebra, functions, and word-problem strategy with short quizzes after each lesson.",
    difficulty: "beginner",
    estimatedHours: 8,
    thumbnailUrl: "/course-thumbnails/mathematics.png",
    isFeatured: true,
    isPublished: true,
  },
  {
    id: "course:english-for-academic-success",
    slug: "english-for-academic-success",
    title: "English for Academic Success",
    summary:
      "Build reading, vocabulary, and writing skills for IELTS, essays, and academic communication.",
    description:
      "Students practice active reading, structured paragraphs, vocabulary review, and timed writing basics.",
    difficulty: "beginner",
    estimatedHours: 7,
    thumbnailUrl: "/course-thumbnails/english.png",
    isFeatured: true,
    isPublished: true,
  },
  {
    id: "course:introduction-to-economics",
    slug: "introduction-to-economics",
    title: "Introduction to Economics",
    summary:
      "Learn supply, demand, incentives, and market thinking through student-friendly examples.",
    description:
      "A compact economics course that prepares students for case competitions, business programs, and social-impact analysis.",
    difficulty: "beginner",
    estimatedHours: 6,
    thumbnailUrl: "/course-thumbnails/economics.png",
    isFeatured: false,
    isPublished: true,
  },
  {
    id: "course:university-admission-basics",
    slug: "university-admission-basics",
    title: "University Admission Basics",
    summary:
      "Understand timelines, activities, essays, recommendations, and scholarship planning.",
    description:
      "Students build a simple roadmap for grades 9-11 and learn how to connect opportunities, courses, and personal goals.",
    difficulty: "beginner",
    estimatedHours: 5,
    thumbnailUrl: "/course-thumbnails/admissions.png",
    isFeatured: true,
    isPublished: true,
  },
] satisfies Array<typeof course.$inferInsert>

export const seedCourseTags = [
  ["course:fundamentals-of-mathematics", "tag:mathematics"],
  ["course:fundamentals-of-mathematics", "tag:stem"],
  ["course:fundamentals-of-mathematics", "tag:olympiads"],
  ["course:english-for-academic-success", "tag:english"],
  ["course:english-for-academic-success", "tag:sat-ielts"],
  ["course:english-for-academic-success", "tag:university-admission"],
  ["course:introduction-to-economics", "tag:economics"],
  ["course:introduction-to-economics", "tag:business"],
  ["course:introduction-to-economics", "tag:finance"],
  ["course:university-admission-basics", "tag:university-admission"],
  ["course:university-admission-basics", "tag:scholarships"],
  ["course:university-admission-basics", "tag:portfolio"],
] satisfies Array<
  [typeof courseTag.$inferInsert.courseId, typeof courseTag.$inferInsert.tagId]
>

export const seedLessons = [
  {
    id: "lesson:math:1",
    courseId: "course:fundamentals-of-mathematics",
    slug: "algebra-foundations",
    title: "Algebra Foundations",
    summary: "Variables, expressions, and equations without guesswork.",
    content:
      "Translate word problems into equations, isolate variables, and check your answer against the original question.",
    videoUrl: "https://example.com/videos/algebra-foundations",
    materials: [
      {
        title: "Algebra practice sheet",
        url: "https://example.com/algebra.pdf",
      },
    ],
    assignmentPrompt: "Solve three linear equations and explain each step.",
    durationMinutes: 28,
    position: 1,
    isPreview: true,
  },
  {
    id: "lesson:math:2",
    courseId: "course:fundamentals-of-mathematics",
    slug: "functions-and-graphs",
    title: "Functions and Graphs",
    summary: "Understand inputs, outputs, slope, and intercepts.",
    content:
      "Read a function as a rule, table, and graph. Connect slope to rate of change in real examples.",
    videoUrl: "https://example.com/videos/functions-and-graphs",
    materials: [],
    assignmentPrompt:
      "Sketch a line from a table of values and label its slope.",
    durationMinutes: 35,
    position: 2,
  },
  {
    id: "lesson:math:3",
    courseId: "course:fundamentals-of-mathematics",
    slug: "problem-solving-strategy",
    title: "Problem-Solving Strategy",
    summary: "Break unfamiliar contest problems into smaller moves.",
    content:
      "Use diagrams, constraints, and substitution to turn hard-looking problems into manageable steps.",
    videoUrl: "https://example.com/videos/problem-solving-strategy",
    materials: [],
    assignmentPrompt: "Write a solution outline before computing the answer.",
    durationMinutes: 32,
    position: 3,
  },
  {
    id: "lesson:english:1",
    courseId: "course:english-for-academic-success",
    slug: "active-reading",
    title: "Active Reading",
    summary: "Read for claims, evidence, and structure.",
    content:
      "Annotate paragraphs by identifying the claim, supporting evidence, and transition words.",
    videoUrl: "https://example.com/videos/active-reading",
    materials: [],
    assignmentPrompt:
      "Annotate one article paragraph using the claim-evidence pattern.",
    durationMinutes: 26,
    position: 1,
    isPreview: true,
  },
  {
    id: "lesson:english:2",
    courseId: "course:english-for-academic-success",
    slug: "academic-paragraphs",
    title: "Academic Paragraphs",
    summary: "Write concise paragraphs with topic sentences and evidence.",
    content:
      "Build paragraphs using a topic sentence, specific evidence, analysis, and a closing link.",
    videoUrl: "https://example.com/videos/academic-paragraphs",
    materials: [],
    assignmentPrompt:
      "Draft one paragraph responding to a short reading prompt.",
    durationMinutes: 30,
    position: 2,
  },
  {
    id: "lesson:english:3",
    courseId: "course:english-for-academic-success",
    slug: "ielts-style-vocabulary",
    title: "IELTS-Style Vocabulary",
    summary: "Learn vocabulary through context, collocations, and review.",
    content:
      "Use spaced repetition and example sentences to remember academic vocabulary in context.",
    videoUrl: "https://example.com/videos/ielts-vocabulary",
    materials: [],
    assignmentPrompt: "Create five example sentences using new academic words.",
    durationMinutes: 22,
    position: 3,
  },
  {
    id: "lesson:economics:1",
    courseId: "course:introduction-to-economics",
    slug: "incentives-and-scarcity",
    title: "Incentives and Scarcity",
    summary: "Why choices have tradeoffs.",
    content:
      "Economics starts with scarcity: limited time, money, and attention. Incentives shape how people choose.",
    videoUrl: "https://example.com/videos/incentives-scarcity",
    materials: [],
    assignmentPrompt: "Describe one school decision using costs and benefits.",
    durationMinutes: 24,
    position: 1,
    isPreview: true,
  },
  {
    id: "lesson:economics:2",
    courseId: "course:introduction-to-economics",
    slug: "supply-and-demand",
    title: "Supply and Demand",
    summary: "Understand market movement with simple graphs.",
    content:
      "Demand shows buyers' willingness to purchase; supply shows sellers' willingness to produce.",
    videoUrl: "https://example.com/videos/supply-demand",
    materials: [],
    assignmentPrompt: "Explain what happens to price when demand increases.",
    durationMinutes: 31,
    position: 2,
  },
  {
    id: "lesson:admissions:1",
    courseId: "course:university-admission-basics",
    slug: "building-a-roadmap",
    title: "Building a Roadmap",
    summary: "Turn grade, goals, and deadlines into a practical plan.",
    content:
      "Map test dates, activities, applications, and reflection time across the school year.",
    videoUrl: "https://example.com/videos/admissions-roadmap",
    materials: [
      {
        title: "Application roadmap template",
        url: "https://example.com/admissions-roadmap.pdf",
      },
    ],
    assignmentPrompt:
      "Draft a three-month roadmap with one course and two opportunities.",
    durationMinutes: 34,
    position: 1,
    isPreview: true,
  },
  {
    id: "lesson:admissions:2",
    courseId: "course:university-admission-basics",
    slug: "activities-and-fit",
    title: "Activities and Fit",
    summary: "Choose opportunities that support your story.",
    content:
      "Strong activities connect your interests, initiative, contribution, and future direction.",
    videoUrl: "https://example.com/videos/activities-fit",
    materials: [],
    assignmentPrompt:
      "Pick two opportunities and explain how they fit your goals.",
    durationMinutes: 27,
    position: 2,
  },
] satisfies Array<typeof lesson.$inferInsert>

export const seedQuizQuestions = [
  {
    id: "quiz-question:math:1:1",
    lessonId: "lesson:math:1",
    type: "single_choice",
    prompt: "What is the first step when solving 3x + 5 = 20?",
    explanation: "Undo addition before division: subtract 5 from both sides.",
    position: 1,
  },
  {
    id: "quiz-question:math:2:1",
    lessonId: "lesson:math:2",
    type: "single_choice",
    prompt: "In y = 2x + 3, what does 2 represent?",
    explanation: "The coefficient of x is the slope, or rate of change.",
    position: 1,
  },
  {
    id: "quiz-question:english:1:1",
    lessonId: "lesson:english:1",
    type: "single_choice",
    prompt: "Which annotation best captures a paragraph's main purpose?",
    explanation: "Academic reading starts by identifying the central claim.",
    position: 1,
  },
  {
    id: "quiz-question:economics:1:1",
    lessonId: "lesson:economics:1",
    type: "single_choice",
    prompt: "Scarcity means that people must...",
    explanation: "Scarcity creates tradeoffs because resources are limited.",
    position: 1,
  },
  {
    id: "quiz-question:admissions:1:1",
    lessonId: "lesson:admissions:1",
    type: "single_choice",
    prompt: "A useful roadmap should connect goals with...",
    explanation: "Roadmaps turn goals into dated actions and milestones.",
    position: 1,
  },
] satisfies Array<typeof quizQuestion.$inferInsert>

export const seedQuizOptions = [
  {
    id: "quiz-option:math:1:1:a",
    questionId: "quiz-question:math:1:1",
    label: "Subtract 5 from both sides",
    isCorrect: true,
    position: 1,
  },
  {
    id: "quiz-option:math:1:1:b",
    questionId: "quiz-question:math:1:1",
    label: "Divide both sides by 5",
    isCorrect: false,
    position: 2,
  },
  {
    id: "quiz-option:math:2:1:a",
    questionId: "quiz-question:math:2:1",
    label: "The slope",
    isCorrect: true,
    position: 1,
  },
  {
    id: "quiz-option:math:2:1:b",
    questionId: "quiz-question:math:2:1",
    label: "The y-intercept",
    isCorrect: false,
    position: 2,
  },
  {
    id: "quiz-option:english:1:1:a",
    questionId: "quiz-question:english:1:1",
    label: "The central claim",
    isCorrect: true,
    position: 1,
  },
  {
    id: "quiz-option:english:1:1:b",
    questionId: "quiz-question:english:1:1",
    label: "The longest sentence",
    isCorrect: false,
    position: 2,
  },
  {
    id: "quiz-option:economics:1:1:a",
    questionId: "quiz-question:economics:1:1",
    label: "Choose between tradeoffs",
    isCorrect: true,
    position: 1,
  },
  {
    id: "quiz-option:economics:1:1:b",
    questionId: "quiz-question:economics:1:1",
    label: "Ignore opportunity cost",
    isCorrect: false,
    position: 2,
  },
  {
    id: "quiz-option:admissions:1:1:a",
    questionId: "quiz-question:admissions:1:1",
    label: "Dated actions and milestones",
    isCorrect: true,
    position: 1,
  },
  {
    id: "quiz-option:admissions:1:1:b",
    questionId: "quiz-question:admissions:1:1",
    label: "Only a final university list",
    isCorrect: false,
    position: 2,
  },
] satisfies Array<typeof quizOption.$inferInsert>
