/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewWriteOffsRouteImport } from './routes/review.write-offs'
import { Route as ReviewHistoryRouteImport } from './routes/review.history'
import { Route as ReviewAnalyticsRouteImport } from './routes/review.analytics'
import { Route as ReviewWriteOffsIndexRouteImport } from './routes/review.write-offs.index'
import { Route as ReviewWriteOffsIdRouteImport } from './routes/review.write-offs.$id'
import { Route as ApiMobileWriteOffRequestsRouteImport } from './routes/api/mobile/write-off-requests'
import { Route as ApiMobileMeRouteImport } from './routes/api/mobile/me'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMobileWriteOffRequestsMineRouteImport } from './routes/api/mobile/write-off-requests/mine'
import { Route as ApiMobileWriteOffRequestsIdRouteImport } from './routes/api/mobile/write-off-requests/$id'
import { Route as ApiMobileFilesWriteOffPhotoRouteImport } from './routes/api/mobile/files/write-off-photo'
import { Route as ApiMobileCatalogWriteOffCategoriesRouteImport } from './routes/api/mobile/catalog/write-off-categories'
import { Route as ApiMobileCatalogProductsRouteImport } from './routes/api/mobile/catalog/products'
import { Route as ApiMobileCatalogProductCategoriesRouteImport } from './routes/api/mobile/catalog/product-categories'
import { Route as ApiMobileCatalogPointsOfSaleRouteImport } from './routes/api/mobile/catalog/points-of-sale'
import { Route as ApiMobileCatalogEmployeesRouteImport } from './routes/api/mobile/catalog/employees'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewWriteOffsRoute = ReviewWriteOffsRouteImport.update({
  id: '/write-offs',
  path: '/write-offs',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewHistoryRoute = ReviewHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewAnalyticsRoute = ReviewAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewWriteOffsIndexRoute = ReviewWriteOffsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewWriteOffsRoute,
} as any)
const ReviewWriteOffsIdRoute = ReviewWriteOffsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReviewWriteOffsRoute,
} as any)
const ApiMobileWriteOffRequestsRoute =
  ApiMobileWriteOffRequestsRouteImport.update({
    id: '/api/mobile/write-off-requests',
    path: '/api/mobile/write-off-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileMeRoute = ApiMobileMeRouteImport.update({
  id: '/api/mobile/me',
  path: '/api/mobile/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileWriteOffRequestsMineRoute =
  ApiMobileWriteOffRequestsMineRouteImport.update({
    id: '/mine',
    path: '/mine',
    getParentRoute: () => ApiMobileWriteOffRequestsRoute,
  } as any)
const ApiMobileWriteOffRequestsIdRoute =
  ApiMobileWriteOffRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiMobileWriteOffRequestsRoute,
  } as any)
const ApiMobileFilesWriteOffPhotoRoute =
  ApiMobileFilesWriteOffPhotoRouteImport.update({
    id: '/api/mobile/files/write-off-photo',
    path: '/api/mobile/files/write-off-photo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileCatalogWriteOffCategoriesRoute =
  ApiMobileCatalogWriteOffCategoriesRouteImport.update({
    id: '/api/mobile/catalog/write-off-categories',
    path: '/api/mobile/catalog/write-off-categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileCatalogProductsRoute =
  ApiMobileCatalogProductsRouteImport.update({
    id: '/api/mobile/catalog/products',
    path: '/api/mobile/catalog/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileCatalogProductCategoriesRoute =
  ApiMobileCatalogProductCategoriesRouteImport.update({
    id: '/api/mobile/catalog/product-categories',
    path: '/api/mobile/catalog/product-categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileCatalogPointsOfSaleRoute =
  ApiMobileCatalogPointsOfSaleRouteImport.update({
    id: '/api/mobile/catalog/points-of-sale',
    path: '/api/mobile/catalog/points-of-sale',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileCatalogEmployeesRoute =
  ApiMobileCatalogEmployeesRouteImport.update({
    id: '/api/mobile/catalog/employees',
    path: '/api/mobile/catalog/employees',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/review/analytics': typeof ReviewAnalyticsRoute
  '/review/history': typeof ReviewHistoryRoute
  '/review/write-offs': typeof ReviewWriteOffsRouteWithChildren
  '/review/': typeof ReviewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mobile/me': typeof ApiMobileMeRoute
  '/api/mobile/write-off-requests': typeof ApiMobileWriteOffRequestsRouteWithChildren
  '/review/write-offs/$id': typeof ReviewWriteOffsIdRoute
  '/review/write-offs/': typeof ReviewWriteOffsIndexRoute
  '/api/mobile/catalog/employees': typeof ApiMobileCatalogEmployeesRoute
  '/api/mobile/catalog/points-of-sale': typeof ApiMobileCatalogPointsOfSaleRoute
  '/api/mobile/catalog/product-categories': typeof ApiMobileCatalogProductCategoriesRoute
  '/api/mobile/catalog/products': typeof ApiMobileCatalogProductsRoute
  '/api/mobile/catalog/write-off-categories': typeof ApiMobileCatalogWriteOffCategoriesRoute
  '/api/mobile/files/write-off-photo': typeof ApiMobileFilesWriteOffPhotoRoute
  '/api/mobile/write-off-requests/$id': typeof ApiMobileWriteOffRequestsIdRoute
  '/api/mobile/write-off-requests/mine': typeof ApiMobileWriteOffRequestsMineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/review/analytics': typeof ReviewAnalyticsRoute
  '/review/history': typeof ReviewHistoryRoute
  '/review': typeof ReviewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mobile/me': typeof ApiMobileMeRoute
  '/api/mobile/write-off-requests': typeof ApiMobileWriteOffRequestsRouteWithChildren
  '/review/write-offs/$id': typeof ReviewWriteOffsIdRoute
  '/review/write-offs': typeof ReviewWriteOffsIndexRoute
  '/api/mobile/catalog/employees': typeof ApiMobileCatalogEmployeesRoute
  '/api/mobile/catalog/points-of-sale': typeof ApiMobileCatalogPointsOfSaleRoute
  '/api/mobile/catalog/product-categories': typeof ApiMobileCatalogProductCategoriesRoute
  '/api/mobile/catalog/products': typeof ApiMobileCatalogProductsRoute
  '/api/mobile/catalog/write-off-categories': typeof ApiMobileCatalogWriteOffCategoriesRoute
  '/api/mobile/files/write-off-photo': typeof ApiMobileFilesWriteOffPhotoRoute
  '/api/mobile/write-off-requests/$id': typeof ApiMobileWriteOffRequestsIdRoute
  '/api/mobile/write-off-requests/mine': typeof ApiMobileWriteOffRequestsMineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/review/analytics': typeof ReviewAnalyticsRoute
  '/review/history': typeof ReviewHistoryRoute
  '/review/write-offs': typeof ReviewWriteOffsRouteWithChildren
  '/review/': typeof ReviewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mobile/me': typeof ApiMobileMeRoute
  '/api/mobile/write-off-requests': typeof ApiMobileWriteOffRequestsRouteWithChildren
  '/review/write-offs/$id': typeof ReviewWriteOffsIdRoute
  '/review/write-offs/': typeof ReviewWriteOffsIndexRoute
  '/api/mobile/catalog/employees': typeof ApiMobileCatalogEmployeesRoute
  '/api/mobile/catalog/points-of-sale': typeof ApiMobileCatalogPointsOfSaleRoute
  '/api/mobile/catalog/product-categories': typeof ApiMobileCatalogProductCategoriesRoute
  '/api/mobile/catalog/products': typeof ApiMobileCatalogProductsRoute
  '/api/mobile/catalog/write-off-categories': typeof ApiMobileCatalogWriteOffCategoriesRoute
  '/api/mobile/files/write-off-photo': typeof ApiMobileFilesWriteOffPhotoRoute
  '/api/mobile/write-off-requests/$id': typeof ApiMobileWriteOffRequestsIdRoute
  '/api/mobile/write-off-requests/mine': typeof ApiMobileWriteOffRequestsMineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/privacy'
    | '/review'
    | '/sign-in'
    | '/terms'
    | '/review/analytics'
    | '/review/history'
    | '/review/write-offs'
    | '/review/'
    | '/api/auth/$'
    | '/api/mobile/me'
    | '/api/mobile/write-off-requests'
    | '/review/write-offs/$id'
    | '/review/write-offs/'
    | '/api/mobile/catalog/employees'
    | '/api/mobile/catalog/points-of-sale'
    | '/api/mobile/catalog/product-categories'
    | '/api/mobile/catalog/products'
    | '/api/mobile/catalog/write-off-categories'
    | '/api/mobile/files/write-off-photo'
    | '/api/mobile/write-off-requests/$id'
    | '/api/mobile/write-off-requests/mine'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/review/analytics'
    | '/review/history'
    | '/review'
    | '/api/auth/$'
    | '/api/mobile/me'
    | '/api/mobile/write-off-requests'
    | '/review/write-offs/$id'
    | '/review/write-offs'
    | '/api/mobile/catalog/employees'
    | '/api/mobile/catalog/points-of-sale'
    | '/api/mobile/catalog/product-categories'
    | '/api/mobile/catalog/products'
    | '/api/mobile/catalog/write-off-categories'
    | '/api/mobile/files/write-off-photo'
    | '/api/mobile/write-off-requests/$id'
    | '/api/mobile/write-off-requests/mine'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/privacy'
    | '/review'
    | '/sign-in'
    | '/terms'
    | '/review/analytics'
    | '/review/history'
    | '/review/write-offs'
    | '/review/'
    | '/api/auth/$'
    | '/api/mobile/me'
    | '/api/mobile/write-off-requests'
    | '/review/write-offs/$id'
    | '/review/write-offs/'
    | '/api/mobile/catalog/employees'
    | '/api/mobile/catalog/points-of-sale'
    | '/api/mobile/catalog/product-categories'
    | '/api/mobile/catalog/products'
    | '/api/mobile/catalog/write-off-categories'
    | '/api/mobile/files/write-off-photo'
    | '/api/mobile/write-off-requests/$id'
    | '/api/mobile/write-off-requests/mine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewRoute: typeof ReviewRouteWithChildren
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMobileMeRoute: typeof ApiMobileMeRoute
  ApiMobileWriteOffRequestsRoute: typeof ApiMobileWriteOffRequestsRouteWithChildren
  ApiMobileCatalogEmployeesRoute: typeof ApiMobileCatalogEmployeesRoute
  ApiMobileCatalogPointsOfSaleRoute: typeof ApiMobileCatalogPointsOfSaleRoute
  ApiMobileCatalogProductCategoriesRoute: typeof ApiMobileCatalogProductCategoriesRoute
  ApiMobileCatalogProductsRoute: typeof ApiMobileCatalogProductsRoute
  ApiMobileCatalogWriteOffCategoriesRoute: typeof ApiMobileCatalogWriteOffCategoriesRoute
  ApiMobileFilesWriteOffPhotoRoute: typeof ApiMobileFilesWriteOffPhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/write-offs': {
      id: '/review/write-offs'
      path: '/write-offs'
      fullPath: '/review/write-offs'
      preLoaderRoute: typeof ReviewWriteOffsRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/history': {
      id: '/review/history'
      path: '/history'
      fullPath: '/review/history'
      preLoaderRoute: typeof ReviewHistoryRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/analytics': {
      id: '/review/analytics'
      path: '/analytics'
      fullPath: '/review/analytics'
      preLoaderRoute: typeof ReviewAnalyticsRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/write-offs/': {
      id: '/review/write-offs/'
      path: '/'
      fullPath: '/review/write-offs/'
      preLoaderRoute: typeof ReviewWriteOffsIndexRouteImport
      parentRoute: typeof ReviewWriteOffsRoute
    }
    '/review/write-offs/$id': {
      id: '/review/write-offs/$id'
      path: '/$id'
      fullPath: '/review/write-offs/$id'
      preLoaderRoute: typeof ReviewWriteOffsIdRouteImport
      parentRoute: typeof ReviewWriteOffsRoute
    }
    '/api/mobile/write-off-requests': {
      id: '/api/mobile/write-off-requests'
      path: '/api/mobile/write-off-requests'
      fullPath: '/api/mobile/write-off-requests'
      preLoaderRoute: typeof ApiMobileWriteOffRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/me': {
      id: '/api/mobile/me'
      path: '/api/mobile/me'
      fullPath: '/api/mobile/me'
      preLoaderRoute: typeof ApiMobileMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/write-off-requests/mine': {
      id: '/api/mobile/write-off-requests/mine'
      path: '/mine'
      fullPath: '/api/mobile/write-off-requests/mine'
      preLoaderRoute: typeof ApiMobileWriteOffRequestsMineRouteImport
      parentRoute: typeof ApiMobileWriteOffRequestsRoute
    }
    '/api/mobile/write-off-requests/$id': {
      id: '/api/mobile/write-off-requests/$id'
      path: '/$id'
      fullPath: '/api/mobile/write-off-requests/$id'
      preLoaderRoute: typeof ApiMobileWriteOffRequestsIdRouteImport
      parentRoute: typeof ApiMobileWriteOffRequestsRoute
    }
    '/api/mobile/files/write-off-photo': {
      id: '/api/mobile/files/write-off-photo'
      path: '/api/mobile/files/write-off-photo'
      fullPath: '/api/mobile/files/write-off-photo'
      preLoaderRoute: typeof ApiMobileFilesWriteOffPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/catalog/write-off-categories': {
      id: '/api/mobile/catalog/write-off-categories'
      path: '/api/mobile/catalog/write-off-categories'
      fullPath: '/api/mobile/catalog/write-off-categories'
      preLoaderRoute: typeof ApiMobileCatalogWriteOffCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/catalog/products': {
      id: '/api/mobile/catalog/products'
      path: '/api/mobile/catalog/products'
      fullPath: '/api/mobile/catalog/products'
      preLoaderRoute: typeof ApiMobileCatalogProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/catalog/product-categories': {
      id: '/api/mobile/catalog/product-categories'
      path: '/api/mobile/catalog/product-categories'
      fullPath: '/api/mobile/catalog/product-categories'
      preLoaderRoute: typeof ApiMobileCatalogProductCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/catalog/points-of-sale': {
      id: '/api/mobile/catalog/points-of-sale'
      path: '/api/mobile/catalog/points-of-sale'
      fullPath: '/api/mobile/catalog/points-of-sale'
      preLoaderRoute: typeof ApiMobileCatalogPointsOfSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/catalog/employees': {
      id: '/api/mobile/catalog/employees'
      path: '/api/mobile/catalog/employees'
      fullPath: '/api/mobile/catalog/employees'
      preLoaderRoute: typeof ApiMobileCatalogEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReviewWriteOffsRouteChildren {
  ReviewWriteOffsIdRoute: typeof ReviewWriteOffsIdRoute
  ReviewWriteOffsIndexRoute: typeof ReviewWriteOffsIndexRoute
}

const ReviewWriteOffsRouteChildren: ReviewWriteOffsRouteChildren = {
  ReviewWriteOffsIdRoute: ReviewWriteOffsIdRoute,
  ReviewWriteOffsIndexRoute: ReviewWriteOffsIndexRoute,
}

const ReviewWriteOffsRouteWithChildren = ReviewWriteOffsRoute._addFileChildren(
  ReviewWriteOffsRouteChildren,
)

interface ReviewRouteChildren {
  ReviewAnalyticsRoute: typeof ReviewAnalyticsRoute
  ReviewHistoryRoute: typeof ReviewHistoryRoute
  ReviewWriteOffsRoute: typeof ReviewWriteOffsRouteWithChildren
  ReviewIndexRoute: typeof ReviewIndexRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewAnalyticsRoute: ReviewAnalyticsRoute,
  ReviewHistoryRoute: ReviewHistoryRoute,
  ReviewWriteOffsRoute: ReviewWriteOffsRouteWithChildren,
  ReviewIndexRoute: ReviewIndexRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

interface ApiMobileWriteOffRequestsRouteChildren {
  ApiMobileWriteOffRequestsIdRoute: typeof ApiMobileWriteOffRequestsIdRoute
  ApiMobileWriteOffRequestsMineRoute: typeof ApiMobileWriteOffRequestsMineRoute
}

const ApiMobileWriteOffRequestsRouteChildren: ApiMobileWriteOffRequestsRouteChildren =
  {
    ApiMobileWriteOffRequestsIdRoute: ApiMobileWriteOffRequestsIdRoute,
    ApiMobileWriteOffRequestsMineRoute: ApiMobileWriteOffRequestsMineRoute,
  }

const ApiMobileWriteOffRequestsRouteWithChildren =
  ApiMobileWriteOffRequestsRoute._addFileChildren(
    ApiMobileWriteOffRequestsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewRoute: ReviewRouteWithChildren,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMobileMeRoute: ApiMobileMeRoute,
  ApiMobileWriteOffRequestsRoute: ApiMobileWriteOffRequestsRouteWithChildren,
  ApiMobileCatalogEmployeesRoute: ApiMobileCatalogEmployeesRoute,
  ApiMobileCatalogPointsOfSaleRoute: ApiMobileCatalogPointsOfSaleRoute,
  ApiMobileCatalogProductCategoriesRoute:
    ApiMobileCatalogProductCategoriesRoute,
  ApiMobileCatalogProductsRoute: ApiMobileCatalogProductsRoute,
  ApiMobileCatalogWriteOffCategoriesRoute:
    ApiMobileCatalogWriteOffCategoriesRoute,
  ApiMobileFilesWriteOffPhotoRoute: ApiMobileFilesWriteOffPhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
