/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteOffsRouteImport } from './routes/write-offs'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewHistoryRouteImport } from './routes/review.history'
import { Route as ReviewAnalyticsRouteImport } from './routes/review.analytics'
import { Route as ReviewWriteOffsRouteImport } from './routes/review.write-offs'
import { Route as ReviewWriteOffsIndexRouteImport } from './routes/review.write-offs.index'
import { Route as ReviewWriteOffsIdRouteImport } from './routes/review.write-offs.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const WriteOffsRoute = WriteOffsRouteImport.update({
  id: '/write-offs',
  path: '/write-offs',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewHistoryRoute = ReviewHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewAnalyticsRoute = ReviewAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewWriteOffsRoute = ReviewWriteOffsRouteImport.update({
  id: '/write-offs',
  path: '/write-offs',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewWriteOffsIndexRoute = ReviewWriteOffsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewWriteOffsRoute,
} as any)
const ReviewWriteOffsIdRoute = ReviewWriteOffsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReviewWriteOffsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/write-offs': typeof WriteOffsRoute
  '/review/write-offs': typeof ReviewWriteOffsRouteWithChildren
  '/review/analytics': typeof ReviewAnalyticsRoute
  '/review/history': typeof ReviewHistoryRoute
  '/review/': typeof ReviewIndexRoute
  '/review/write-offs/$id': typeof ReviewWriteOffsIdRoute
  '/review/write-offs/': typeof ReviewWriteOffsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/write-offs': typeof WriteOffsRoute
  '/review/analytics': typeof ReviewAnalyticsRoute
  '/review/history': typeof ReviewHistoryRoute
  '/review': typeof ReviewIndexRoute
  '/review/write-offs/$id': typeof ReviewWriteOffsIdRoute
  '/review/write-offs': typeof ReviewWriteOffsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/write-offs': typeof WriteOffsRoute
  '/review/write-offs': typeof ReviewWriteOffsRouteWithChildren
  '/review/analytics': typeof ReviewAnalyticsRoute
  '/review/history': typeof ReviewHistoryRoute
  '/review/': typeof ReviewIndexRoute
  '/review/write-offs/$id': typeof ReviewWriteOffsIdRoute
  '/review/write-offs/': typeof ReviewWriteOffsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/privacy'
    | '/review'
    | '/sign-in'
    | '/terms'
    | '/write-offs'
    | '/review/write-offs'
    | '/review/analytics'
    | '/review/history'
    | '/review/'
    | '/review/write-offs/$id'
    | '/review/write-offs/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/write-offs'
    | '/review/analytics'
    | '/review/history'
    | '/review'
    | '/review/write-offs/$id'
    | '/review/write-offs'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/privacy'
    | '/review'
    | '/sign-in'
    | '/terms'
    | '/write-offs'
    | '/review/write-offs'
    | '/review/analytics'
    | '/review/history'
    | '/review/'
    | '/review/write-offs/$id'
    | '/review/write-offs/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewRoute: typeof ReviewRouteWithChildren
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  WriteOffsRoute: typeof WriteOffsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write-offs': {
      id: '/write-offs'
      path: '/write-offs'
      fullPath: '/write-offs'
      preLoaderRoute: typeof WriteOffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/history': {
      id: '/review/history'
      path: '/history'
      fullPath: '/review/history'
      preLoaderRoute: typeof ReviewHistoryRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/analytics': {
      id: '/review/analytics'
      path: '/analytics'
      fullPath: '/review/analytics'
      preLoaderRoute: typeof ReviewAnalyticsRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/write-offs': {
      id: '/review/write-offs'
      path: '/write-offs'
      fullPath: '/review/write-offs'
      preLoaderRoute: typeof ReviewWriteOffsRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/write-offs/': {
      id: '/review/write-offs/'
      path: '/'
      fullPath: '/review/write-offs/'
      preLoaderRoute: typeof ReviewWriteOffsIndexRouteImport
      parentRoute: typeof ReviewWriteOffsRoute
    }
    '/review/write-offs/$id': {
      id: '/review/write-offs/$id'
      path: '/$id'
      fullPath: '/review/write-offs/$id'
      preLoaderRoute: typeof ReviewWriteOffsIdRouteImport
      parentRoute: typeof ReviewWriteOffsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReviewWriteOffsRouteChildren {
  ReviewWriteOffsIndexRoute: typeof ReviewWriteOffsIndexRoute
  ReviewWriteOffsIdRoute: typeof ReviewWriteOffsIdRoute
}

const ReviewWriteOffsRouteChildren: ReviewWriteOffsRouteChildren = {
  ReviewWriteOffsIndexRoute: ReviewWriteOffsIndexRoute,
  ReviewWriteOffsIdRoute: ReviewWriteOffsIdRoute,
}

const ReviewWriteOffsRouteWithChildren =
  ReviewWriteOffsRoute._addFileChildren(ReviewWriteOffsRouteChildren)

interface ReviewRouteChildren {
  ReviewWriteOffsRoute: typeof ReviewWriteOffsRouteWithChildren
  ReviewAnalyticsRoute: typeof ReviewAnalyticsRoute
  ReviewHistoryRoute: typeof ReviewHistoryRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewWriteOffsRoute: ReviewWriteOffsRouteWithChildren,
  ReviewAnalyticsRoute: ReviewAnalyticsRoute,
  ReviewHistoryRoute: ReviewHistoryRoute,
  ReviewIndexRoute: ReviewIndexRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewRoute: ReviewRouteWithChildren,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  WriteOffsRoute: WriteOffsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
